# stack_allocation/Makefile
#
# Makefile for stack allocation example
# 
# Nitsan Shai
# nshai@google.com

stack_allocation: main.c # run "make stack_allocation" to run code
	gcc -o main main.c # runs main
	
heap_allocation: ../heap_allocation/main.c #2nd line is a tab
	gcc -o myheap ../heap_allocation/main.c 
	
	